data:
  source_url: "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip"
  local_dir: data
  data_file: data.zip
  unzip_data_dir: data2
  parent_data_dir: PetImages
  bad_data_dir: bad_data
  model_dir: model
  init_model_file: init_model.h5


params:
  img_shape: [180,180,3]
  lr: 0.001
  loss: sparse_categorical_crossentropy
  metrics: ["accuracy"]



